[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


[project]
name = "pysst"
version = "0.0.1"
dependencies = [
    "requests",
    'importlib-metadata; python_version>"3.7"',
    'matplotlib',
    'notebook',
    'numpy',
    'xarray',
    'geopy',

]
